{% set name = "dotenv" %}
{% set version = "2.8.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: c5944793349ae03c432e1780a2ca929d60b88c7d14d52d630db0508c3a8a17d8

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'
    - dotenv --help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Ruby gem to load environment variables from `.env`
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/bkeepers/dotenv

extra:
  recipe-maintainers:
    - sodre
    - mxr-conda
