{% set name = "dotenv" %}
{% set version = "2.7.6" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 2451ed5e8e43776d7a787e51d6f8903b98e446146c7ad143d5678cc2c409d547 

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r dotenv -e 'exit 0'
    - dotenv -V

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: 'Ruby gem to load environment variables from `.env`'
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/bkeepers/dotenv

extra:
  recipe-maintainers:
    - sodre
    - rluria14
    - mxr-conda
