travis:
  secure:
    BINSTAR_TOKEN: MNWYjmE7GjVjb770rlr51O9HTjw10/CVz3wxiJD+JLBhzBbMKFOFfXRjJic1U3CRED01KKrNiETWFUkP9KfXRC1GKpdyz5406QpU0v4drD4Unw92NzySExlCMh0nlZP010g/98Z+yDVNKDJbihdZmjytXxwRYRrhqGt0Og6D75uVluTJUqSXjZCzvZTEHgJTML2UMrX1C0/tjxe3eH/eoFcVGGqKWb8cxoGUA97L3tyaTAVCVEA/V1bl/EYhIyQAh1pv5V5xlydPepAGdudIE85xWaLny02d3IdwbOUfppFUNMC+uCLPxDqV+ckw/I7nRrd4VrOgSoqUICQozOVM1djdcDCGcuPUMgXMeTAR7QJZACFbNdGMX6PaQh9IHy0Nrv8M4K324TcMaPSfztJsWL90wVuF+meKzstYdtcZeQMfmtzjzDDUi1fuHHx0hgahpCu6R7zjIAiuWQUMaS/BU5lEomG7Xnz4Dz2+4/e1NbaAM/qkFfLuofYGEnn2mcoeP70BqNoDqjveFhs8UD3VWs3+lGI7jQ6Q+3UwZfKgrKOcUIjfv59ws6kSUxP0Tr+Vg2mTP6DuIKTyqik1VS4zGWgrWIYUa6dryL2bG77VO4woheiqLKMK5UOKPiBn65K1WbZIN2tiTHUjG4B/zSYXbrn2NrGoNiag80g6LIKtm9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
